import type {
  IEPPlan,
  IEPGoal,
  IEPService,
  ProgressRecord,
  ApprovalLog,
  ParentSignature,
  EvaluationMethod,
  EvaluationFrequency,
  Priority,
  IEPStatus,
} from './types';

// Helper to create dates
const d = (offsetDays: number) => {
  const date = new Date('2025-01-01');
  date.setDate(date.getDate() + offsetDays);
  return date.toISOString().split('T')[0];
};

export const mockStudents = [
  { id: 's1', name: '王小明', class: '启智一班', number: 'XH202301' },
  { id: 's2', name: '李小红', class: '启智一班', number: 'XH202302' },
  { id: 's3', name: '张小雨', class: '启智二班', number: 'XH202303' },
  { id: 's4', name: '刘小强', class: '启智二班', number: 'XH202304' },
  { id: 's5', name: '陈小静', class: '启智三班', number: 'XH202305' },
  { id: 's6', name: '赵小军', class: '启智三班', number: 'XH202306' },
  { id: 's7', name: '孙小丽', class: '启智一班', number: 'XH202307' },
  { id: 's8', name: '周小辉', class: '启智二班', number: 'XH202308' },
  { id: 's9', name: '吴小芳', class: '启智三班', number: 'XH202309' },
  { id: 's10', name: '马小龙', class: '启智一班', number: 'XH202310' },
  { id: 's11', name: '郑小娟', class: '启智二班', number: 'XH202311' },
  { id: 's12', name: '黄小波', class: '启智三班', number: 'XH202312' },
  { id: 's13', name: '林小婷', class: '启智一班', number: 'XH202313' },
  { id: 's14', name: '何小亮', class: '启智二班', number: 'XH202314' },
  { id: 's15', name: '罗小霞', class: '启智三班', number: 'XH202315' },
];

export const mockTeachers = ['张老师', '李老师', '王老师', '刘老师', '陈老师', '赵老师', '孙老师'];

/* Teacher ID mapping for participate-view demo */
export const teacherNameToId: Record<string, string> = {
  '张老师': 't1',
  '李老师': 't2',
  '王老师': 't3',
  '刘老师': 't4',
  '陈老师': 't5',
  '赵老师': 't6',
  '孙老师': 't7',
};

export const mockIEPPlans: IEPPlan[] = [
  {
    id: 'iep1',
    plan_code: 'IEP-2025-001',
    title: '王小明2025上半年个别化教育计划',
    student_id: 's1',
    student_name: '王小明',
    student_class: '启智一班',
    student_number: 'XH202301',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(14),
    end_date: d(194),
    primary_teacher: '张老师',
    team_members: ['李老师', '王老师', '陈老师'],
    status: '执行中',
    progress_percent: 65,
    goals_count: 6,
    signed: true,
    signature_status: '已签名',
    current_levels: {
      '认知发展': '注意力持续时间短，约5-8分钟，需要多次提醒才能完成任务。对视觉提示有较好的反应。',
      '语言能力': '能说简单的两字词语，表达需求时使用 gestures 较多。对熟悉的故事有反应。',
      '运动能力': '大肌肉发展良好，能跑跳。精细动作较弱，握笔困难。',
      '社交适应': '愿意与熟悉的同伴互动，但缺乏主动交往能力。能理解简单规则。',
      '生活自理': '能独立吃饭，但需要协助穿衣。能认识自己的物品。',
      '情绪行为': '偶尔有情绪爆发，但能在安抚下平静。对变化适应较慢。',
    },
    teaching_adaptations: '使用视觉提示卡、分段教学、多感官教学法、结构化教学环境',
    assistive_tech: '视觉提示卡、计时器、平板电脑辅助沟通软件',
    transition_plan: '逐步减少辅助，增加独立完成任务的机会',
    created_at: d(0),
    updated_at: d(10),
  },
  {
    id: 'iep2',
    plan_code: 'IEP-2025-002',
    title: '李小红2025上半年个别化教育计划',
    student_id: 's2',
    student_name: '李小红',
    student_class: '启智一班',
    student_number: 'XH202302',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(21),
    end_date: d(201),
    primary_teacher: '李老师',
    team_members: ['张老师', '赵老师'],
    status: '审核中',
    progress_percent: 0,
    goals_count: 5,
    signed: false,
    signature_status: '待签名',
    current_levels: {
      '认知发展': '能完成简单配对和分类任务，数字概念1-10基本掌握。',
      '语言能力': '能说完整句子，但语法有误。能理解两步指令。',
      '运动能力': '协调性较好，能骑三轮车。能沿直线走路。',
      '社交适应': '喜欢与同伴玩耍，但常主导游戏。需要学习分享和轮流。',
      '生活自理': '能独立穿衣、洗漱。需要帮助系鞋带。',
      '情绪行为': '情绪较稳定，受挫时会寻求成人帮助。',
    },
    teaching_adaptations: '社会故事法、角色扮演、正向行为支持',
    assistive_tech: '社会故事绘本、情绪卡片',
    transition_plan: '增加与普通班级融合活动的机会',
    created_at: d(5),
    updated_at: d(15),
  },
  {
    id: 'iep3',
    plan_code: 'IEP-2025-003',
    title: '张小雨2025上半年个别化教育计划',
    student_id: 's3',
    student_name: '张小雨',
    student_class: '启智二班',
    student_number: 'XH202303',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(7),
    end_date: d(187),
    primary_teacher: '王老师',
    team_members: ['刘老师', '陈老师'],
    status: '已通过',
    progress_percent: 0,
    goals_count: 7,
    signed: false,
    signature_status: '待签名',
    current_levels: {
      '认知发展': '注意力持续约10分钟，能完成简单拼图。对颜色、形状有较好的辨识能力。',
      '语言能力': '语言表达能力有限，主要使用单词和短语。能理解日常用语。',
      '运动能力': '大肌肉发展一般，平衡感需加强。精细动作有进步，能握笔涂鸦。',
      '社交适应': '对同伴互动有兴趣但方式不当，需要教导适当的社交技巧。',
      '生活自理': '在提示下能完成洗手、吃饭等自理活动。',
      '情绪行为': '有时会有哭闹行为，需要情绪调节策略的教导。',
    },
    teaching_adaptations: '结构化教学、视觉时间表、正向行为干预',
    assistive_tech: '图片交换沟通系统(PECS)、感觉统合器材',
    transition_plan: '逐步从结构化环境过渡到自然情境',
    created_at: d(3),
    updated_at: d(12),
  },
  {
    id: 'iep4',
    plan_code: 'IEP-2025-004',
    title: '刘小强2025上半年个别化教育计划',
    student_id: 's4',
    student_name: '刘小强',
    student_class: '启智二班',
    student_number: 'XH202304',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(30),
    end_date: d(210),
    primary_teacher: '刘老师',
    team_members: ['王老师', '赵老师', '孙老师'],
    status: '草稿',
    progress_percent: 0,
    goals_count: 5,
    signed: false,
    signature_status: '不需要',
    current_levels: {
      '认知发展': '对数字和字母有初步认识，能完成1-5的数数。注意力分散较快。',
      '语言能力': '能说简单词语，发音不太清晰。能理解一步指令。',
      '运动能力': '喜欢跑跳活动，但平衡感不足。精细动作发展中，能握笔画线。',
      '社交适应': '与同伴互动较少，更喜欢独自活动。对成人有依赖。',
      '生活自理': '能独立吃饭，穿衣需要部分协助。能辨认自己的座位和柜子。',
      '情绪行为': '分离焦虑明显，需要适应时间。情绪表达较为直接。',
    },
    teaching_adaptations: '游戏化教学、感觉统合活动、情境教学',
    assistive_tech: '感觉统合器材、沟通板',
    transition_plan: '建立安全感和信任关系，逐步增加新活动',
    created_at: d(7),
    updated_at: d(7),
  },
  {
    id: 'iep5',
    plan_code: 'IEP-2025-005',
    title: '陈小静2025上半年个别化教育计划',
    student_id: 's5',
    student_name: '陈小静',
    student_class: '启智三班',
    student_number: 'XH202305',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(10),
    end_date: d(190),
    primary_teacher: '陈老师',
    team_members: ['张老师', '李老师'],
    status: '已完成',
    progress_percent: 100,
    goals_count: 6,
    signed: true,
    signature_status: '已签名',
    current_levels: {
      '认知发展': '能完成10以内加减法，分类和排序能力良好。注意力持续时间15分钟。',
      '语言能力': '能进行日常对话，表达较流畅。能复述简单故事。',
      '运动能力': '运动协调能力良好，能跳绳。能熟练使用剪刀。',
      '社交适应': '主动与同伴交往，能遵守游戏规则。能表达自己的情绪。',
      '生活自理': '生活自理能力良好，能整理自己的物品。',
      '情绪行为': '情绪调节能力较好，能使用策略 calm down。',
    },
    teaching_adaptations: '合作学习、情境模拟、自我监控策略',
    assistive_tech: '自我管理工具、社交技能绘本',
    transition_plan: '准备升入下一阶段的适应活动',
    created_at: d(-60),
    updated_at: d(180),
  },
  {
    id: 'iep6',
    plan_code: 'IEP-2025-006',
    title: '赵小军2025上半年个别化教育计划',
    student_id: 's6',
    student_name: '赵小军',
    student_class: '启智三班',
    student_number: 'XH202306',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(20),
    end_date: d(200),
    primary_teacher: '赵老师',
    team_members: ['刘老师', '孙老师'],
    status: '已签名',
    progress_percent: 0,
    goals_count: 5,
    signed: true,
    signature_status: '已签名',
    current_levels: {
      '认知发展': '对因果关系有初步理解，能完成简单序列任务。数字概念1-20。',
      '语言能力': '能说三词句，但表达不够完整。对儿歌有兴趣。',
      '运动能力': '大肌肉发展较好，能单脚站。精细动作需加强。',
      '社交适应': '在引导下能与同伴互动，需要学习轮流和等待。',
      '生活自理': '能独立上厕所，吃饭较整洁。',
      '情绪行为': '容易兴奋，需要 calming strategies。',
    },
    teaching_adaptations: '感觉统合活动、音乐治疗、结构化游戏',
    assistive_tech: '感觉统合器材、音乐播放器',
    transition_plan: '增加自主选择和决策的机会',
    created_at: d(8),
    updated_at: d(18),
  },
  {
    id: 'iep7',
    plan_code: 'IEP-2025-007',
    title: '孙小丽2025上半年个别化教育计划',
    student_id: 's7',
    student_name: '孙小丽',
    student_class: '启智一班',
    student_number: 'XH202307',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(15),
    end_date: d(195),
    primary_teacher: '孙老师',
    team_members: ['张老师', '李老师', '王老师'],
    status: '执行中',
    progress_percent: 45,
    goals_count: 6,
    signed: true,
    signature_status: '已签名',
    current_levels: {
      '认知发展': '注意力持续约8分钟，对视觉学习材料反应良好。能完成简单配对。',
      '语言能力': '能说单词和少数短语，肢体语言丰富。对音乐有反应。',
      '运动能力': '协调性一般，能走楼梯。精细动作发展中，能搭积木。',
      '社交适应': '对成人有较好互动，与同伴互动较少。喜欢被关注。',
      '生活自理': '在提示下能完成洗手、吃饭。',
      '情绪行为': '对环境变化敏感，需要预警和过渡时间。',
    },
    teaching_adaptations: '视觉支持、感觉统合、音乐融入教学',
    assistive_tech: '视觉时间表、感觉统合工具',
    transition_plan: '逐步延长注意力持续时间',
    created_at: d(10),
    updated_at: d(25),
  },
  {
    id: 'iep8',
    plan_code: 'IEP-2025-008',
    title: '周小辉2025上半年个别化教育计划',
    student_id: 's8',
    student_name: '周小辉',
    student_class: '启智二班',
    student_number: 'XH202308',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(25),
    end_date: d(205),
    primary_teacher: '张老师',
    team_members: ['赵老师', '陈老师'],
    status: '已驳回',
    progress_percent: 0,
    goals_count: 4,
    signed: false,
    signature_status: '不需要',
    current_levels: {
      '认知发展': '能辨认常见物品，对颜色有基本认识。注意力分散。',
      '语言能力': '偶尔发出单音节，非语言沟通为主。',
      '运动能力': '能独立行走，跑步易摔倒。精细动作有限。',
      '社交适应': '对熟悉的人微笑，很少主动发起互动。',
      '生活自理': '需要协助完成大部分自理活动。',
      '情绪行为': '偶尔有自伤行为，需要密切观察。',
    },
    teaching_adaptations: '感觉统合、行为干预、多感官教学',
    assistive_tech: '感觉统合器材、安全防护用品',
    transition_plan: '建立基本生活常规',
    created_at: d(12),
    updated_at: d(20),
  },
  {
    id: 'iep9',
    plan_code: 'IEP-2025-009',
    title: '吴小芳2025上半年个别化教育计划',
    student_id: 's9',
    student_name: '吴小芳',
    student_class: '启智三班',
    student_number: 'XH202309',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(18),
    end_date: d(198),
    primary_teacher: '李老师',
    team_members: ['王老师', '刘老师'],
    status: '执行中',
    progress_percent: 80,
    goals_count: 7,
    signed: true,
    signature_status: '已签名',
    current_levels: {
      '认知发展': '能完成10以内数数，对时间概念有初步理解。',
      '语言能力': '能进行简单对话，词汇量逐渐增加。能表达需求。',
      '运动能力': '运动协调良好，能拍球。能使用勺子吃饭。',
      '社交适应': '喜欢与同伴一起玩，需要学习解决冲突。',
      '生活自理': '能自己穿脱简单衣服，帮忙整理玩具。',
      '情绪行为': '情绪表达丰富，偶尔发脾气但能较快恢复。',
    },
    teaching_adaptations: '合作学习、游戏教学、正向行为支持',
    assistive_tech: '教学游戏软件、情绪管理卡片',
    transition_plan: '培养独立完成任务的能力',
    created_at: d(5),
    updated_at: d(30),
  },
  {
    id: 'iep10',
    plan_code: 'IEP-2025-010',
    title: '马小龙2025上半年个别化教育计划',
    student_id: 's10',
    student_name: '马小龙',
    student_class: '启智一班',
    student_number: 'XH202310',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(12),
    end_date: d(192),
    primary_teacher: '王老师',
    team_members: ['张老师', '李老师'],
    status: '草稿',
    progress_percent: 0,
    goals_count: 5,
    signed: false,
    signature_status: '不需要',
    current_levels: {
      '认知发展': '对数字和形状有初步认识。注意力持续约5分钟。',
      '语言能力': '能说少量词语，发音不清。手势沟通较多。',
      '运动能力': '大肌肉发展尚可，喜欢攀爬。精细动作较弱。',
      '社交适应': '对同伴有兴趣，但互动方式需要指导。',
      '生活自理': '能独立吃饭，其他自理活动需要协助。',
      '情绪行为': '活跃好动，需要大量的感觉输入。',
    },
    teaching_adaptations: '感觉统合活动、游戏化学习、视觉支持',
    assistive_tech: '感觉统合器材、视觉提示卡',
    transition_plan: '建立基本生活常规和安全意识',
    created_at: d(2),
    updated_at: d(2),
  },
  {
    id: 'iep11',
    plan_code: 'IEP-2025-011',
    title: '郑小娟2025上半年个别化教育计划',
    student_id: 's11',
    student_name: '郑小娟',
    student_class: '启智二班',
    student_number: 'XH202311',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(22),
    end_date: d(202),
    primary_teacher: '刘老师',
    team_members: ['陈老师', '赵老师'],
    status: '执行中',
    progress_percent: 30,
    goals_count: 6,
    signed: true,
    signature_status: '已签名',
    current_levels: {
      '认知发展': '能完成简单分类和配对，对因果关系有初步理解。',
      '语言能力': '能说简单句子，但语序常混乱。能理解日常指令。',
      '运动能力': '协调性一般，能骑三轮车。能沿直线走。',
      '社交适应': '愿意参与集体活动，需要学习轮流和等待。',
      '生活自理': '能自己吃饭，穿衣需要部分协助。',
      '情绪行为': '对新事物有些抗拒，需要鼓励和支持。',
    },
    teaching_adaptations: '社会故事法、正向行为支持、结构化教学',
    assistive_tech: '社会故事绘本、视觉时间表',
    transition_plan: '增加与普通班级的融合活动',
    created_at: d(8),
    updated_at: d(22),
  },
  {
    id: 'iep12',
    plan_code: 'IEP-2025-012',
    title: '黄小波2025上半年个别化教育计划',
    student_id: 's12',
    student_name: '黄小波',
    student_class: '启智三班',
    student_number: 'XH202312',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(35),
    end_date: d(215),
    primary_teacher: '赵老师',
    team_members: ['孙老师', '张老师'],
    status: '审核中',
    progress_percent: 0,
    goals_count: 5,
    signed: false,
    signature_status: '待签名',
    current_levels: {
      '认知发展': '对颜色、形状有较好的辨识能力。能完成简单拼图。',
      '语言能力': '能说短语和短句，表达需求基本清楚。',
      '运动能力': '运动能力良好，喜欢球类活动。能独立使用剪刀。',
      '社交适应': '与同伴互动良好，有时过于热情需要引导。',
      '生活自理': '自理能力较好，能整理自己的物品。',
      '情绪行为': '情绪较为稳定，受挫时需要鼓励。',
    },
    teaching_adaptations: '合作学习、游戏教学、情境学习',
    assistive_tech: '教学游戏、社交技能卡片',
    transition_plan: '培养独立解决问题的能力',
    created_at: d(10),
    updated_at: d(15),
  },
  {
    id: 'iep13',
    plan_code: 'IEP-2025-013',
    title: '林小婷2025上半年个别化教育计划',
    student_id: 's13',
    student_name: '林小婷',
    student_class: '启智一班',
    student_number: 'XH202313',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(16),
    end_date: d(196),
    primary_teacher: '陈老师',
    team_members: ['李老师', '王老师'],
    status: '已完成',
    progress_percent: 100,
    goals_count: 6,
    signed: true,
    signature_status: '已签名',
    current_levels: {
      '认知发展': '能完成20以内数数，对加减法有初步理解。',
      '语言能力': '能进行较流畅对话，能复述故事主要内容。',
      '运动能力': '协调性良好，能跳绳、拍球。能画出简单图形。',
      '社交适应': '主动与同伴交往，能遵守大多数规则。',
      '生活自理': '生活自理完全独立，能帮忙做简单家务。',
      '情绪行为': '情绪管理良好，能使用适当的情绪表达。',
    },
    teaching_adaptations: '合作学习、项目式学习、自我评估',
    assistive_tech: '学习应用程序、自我管理工具',
    transition_plan: '为下一阶段学习做准备',
    created_at: d(-45),
    updated_at: d(170),
  },
  {
    id: 'iep14',
    plan_code: 'IEP-2025-014',
    title: '何小亮2025上半年个别化教育计划',
    student_id: 's14',
    student_name: '何小亮',
    student_class: '启智二班',
    student_number: 'XH202314',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(28),
    end_date: d(208),
    primary_teacher: '孙老师',
    team_members: ['赵老师', '刘老师'],
    status: '草稿',
    progress_percent: 0,
    goals_count: 5,
    signed: false,
    signature_status: '不需要',
    current_levels: {
      '认知发展': '对常见物品能命名，能完成1-10数数。注意力持续约8分钟。',
      '语言能力': '能说单词和短语，肢体语言辅助沟通。',
      '运动能力': '能跑跳，平衡感需加强。能握笔画简单线条。',
      '社交适应': '对同伴有观察，偶尔模仿同伴行为。',
      '生活自理': '能自己吃饭，穿衣需要协助。',
      '情绪行为': '分离焦虑明显，需要适应时间。',
    },
    teaching_adaptations: '感觉统合、游戏化教学、正向行为支持',
    assistive_tech: '感觉统合器材、图片沟通卡',
    transition_plan: '建立安全感，逐步适应新环境',
    created_at: d(5),
    updated_at: d(5),
  },
  {
    id: 'iep15',
    plan_code: 'IEP-2025-015',
    title: '罗小霞2025上半年个别化教育计划',
    student_id: 's15',
    student_name: '罗小霞',
    student_class: '启智三班',
    student_number: 'XH202315',
    academic_year: '2024-2025',
    semester: '第二学期',
    start_date: d(19),
    end_date: d(199),
    primary_teacher: '张老师',
    team_members: ['李老师', '陈老师'],
    status: '执行中',
    progress_percent: 55,
    goals_count: 6,
    signed: true,
    signature_status: '已签名',
    current_levels: {
      '认知发展': '能完成简单比较（大小、多少），对时间有初步概念。',
      '语言能力': '能进行日常对话，词汇量较丰富。能讲简单故事。',
      '运动能力': '运动协调良好，能单脚跳。能熟练使用铅笔。',
      '社交适应': '与同伴关系良好，能主动帮助他人。',
      '生活自理': '完全自理，能自己准备学习用品。',
      '情绪行为': '情绪稳定，能适当表达各种情绪。',
    },
    teaching_adaptations: '合作学习、项目式学习、同伴支持',
    assistive_tech: '学习软件、教学视频',
    transition_plan: '增加自主学习的机会',
    created_at: d(6),
    updated_at: d(28),
  },
];

// Generate goals for each IEP plan
export const mockGoals: IEPGoal[] = [];
let goalId = 1;

const goalTemplates = [
  { area: '认知' as const, title: '提高视觉注意力持续时间', description: '学生能在课堂活动中保持视觉注意力，跟随教师的教学活动。', target_behavior: '在结构化活动中保持注意力5-10分钟', criteria: '连续3次观察达到80%以上正确率', baseline: '目前注意力持续约3-5分钟', teaching_strategies: '使用视觉提示卡、分段教学、减少环境干扰' },
  { area: '沟通' as const, title: '提升语言表达能力', description: '学生能使用更完整的句子表达需求和想法。', target_behavior: '使用三词句表达需求', criteria: '在日常生活中80%的情况下使用语言表达', baseline: '目前主要使用单词和手势', teaching_strategies: '语言示范、扩展学生的话语、情境教学' },
  { area: '社交' as const, title: '学习适当的社交互动技巧', description: '学生能主动与同伴进行适当的社交互动。', target_behavior: '主动与同伴打招呼并参与共同游戏', criteria: '每天至少有2次主动社交互动', baseline: '很少主动与同伴互动', teaching_strategies: '社会故事法、角色扮演、正向行为支持' },
  { area: '生活自理' as const, title: '提高独立穿衣能力', description: '学生能独立完成穿脱衣物的过程。', target_behavior: '独立穿脱简单衣物', criteria: '连续5天能独立穿脱80%的衣物', baseline: '目前需要协助穿脱大部分衣物', teaching_strategies: '任务分解、视觉提示、逐步减少辅助' },
  { area: '运动' as const, title: '增强精细动作能力', description: '学生能完成需要精细动作协调的任务。', target_behavior: '能握笔写出简单汉字', criteria: '能正确书写5个简单汉字', baseline: '能握笔但书写困难', teaching_strategies: '感觉统合活动、握笔训练、描红练习' },
  { area: '情绪行为' as const, title: '学习情绪调节策略', description: '学生能识别自己的情绪并使用适当策略调节。', target_behavior: '在情绪不好时使用calm down策略', criteria: '80%的情况下能适当调节情绪', baseline: '情绪爆发时需要成人安抚', teaching_strategies: '情绪教育、冷静角、深呼吸练习' },
  { area: '学业' as const, title: '掌握10以内加减法', description: '学生能完成10以内的加法和减法运算。', target_behavior: '正确完成10以内加减法', criteria: '连续3次测试正确率85%以上', baseline: '能完成5以内数数', teaching_strategies: '具体操作物教学、游戏化学习、视觉辅助' },
];

// Teacher pool for assigning goals across different teachers
const allTeachers = ['张老师', '李老师', '王老师', '刘老师', '陈老师', '赵老师', '孙老师'];
const allTeacherIds = ['t1', 't2', 't3', 't4', 't5', 't6', 't7'];

mockIEPPlans.forEach((plan) => {
  const numGoals = plan.goals_count;
  for (let i = 0; i < numGoals; i++) {
    const template = goalTemplates[i % goalTemplates.length];
    const isLongTerm = i < 2;
    // Distribute responsible teachers so that each plan's goals
    // are spread across team members (including primary teacher)
    const possibleTeachers = [plan.primary_teacher, ...plan.team_members];
    const responsibleTeacher = possibleTeachers[i % possibleTeachers.length];
    const responsibleTeacherId = teacherNameToId[responsibleTeacher] || 't1';
    const progress = plan.status === '草稿' || plan.status === '审核中' || plan.status === '已驳回'
      ? 0
      : plan.status === '已完成'
        ? 100
        : Math.max(10, Math.min(95, (plan.progress_percent ?? 0) + Math.floor(Math.random() * 20 - 10)));
    const goalStatus: IEPGoal['status'] = progress >= 100 ? '已完成' : progress > 0 ? '进行中' : '未开始';
    mockGoals.push({
      id: `goal${goalId}`,
      iep_plan_id: plan.id,
      area: template.area,
      title: template.title,
      description: template.description,
      target_behavior: template.target_behavior,
      criteria: template.criteria,
      evaluation_method: (i % 2 === 0 ? '观察记录' : '日常表现') as EvaluationMethod,
      evaluation_frequency: (i % 3 === 0 ? '每周2次' : i % 3 === 1 ? '每周1次' : '每天') as EvaluationFrequency,
      baseline: template.baseline,
      target_score: 5,
      current_score: Math.round((progress / 100) * 5),
      start_date: plan.start_date,
      target_date: plan.end_date,
      priority: (i % 3 === 0 ? '高' : i % 3 === 1 ? '中' : '低') as Priority,
      teaching_strategies: template.teaching_strategies,
      resources: '教学材料、评估工具',
      responsible_teacher: responsibleTeacher,
      responsible_teacher_id: responsibleTeacherId,
      responsible_teacher_name: responsibleTeacher,
      progress_notes: progress > 0 ? `第${i + 1}阶段教学进展顺利，学生表现出积极的学习态度。` : '',
      goal_type: isLongTerm ? '长期目标' : '短期目标',
      progress_percent: Math.max(0, Math.min(100, progress)),
      status: goalStatus,
      created_at: plan.created_at,
      updated_at: plan.updated_at,
    });
    goalId++;
  }
});

// Generate progress records
export const mockProgressRecords: ProgressRecord[] = [];
let recordId = 1;

mockGoals.filter(g => g.progress_percent > 0).forEach((goal) => {
  const numRecords = Math.floor(goal.progress_percent / 20) + 1;
  for (let i = 0; i < numRecords; i++) {
    mockProgressRecords.push({
      id: `pr${recordId}`,
      goal_id: goal.id,
      record_date: d(14 + i * 14),
      score: Math.min(5, Math.round((goal.progress_percent / 100) * 5 + Math.random() * 2 - 1)),
      max_score: 5,
      prompt_level: ['独立', '语言提示', '手势提示', '身体辅助'][Math.floor(Math.random() * 4)],
      notes: ['表现良好', '有进步', '注意力集中', '需要更多练习', '完成质量高'][Math.floor(Math.random() * 5)],
      teacher: goal.responsible_teacher,
      created_at: d(14 + i * 14),
    });
    recordId++;
  }
});

// Generate approval logs
export const mockApprovalLogs: ApprovalLog[] = [];
let logId = 1;

const approvalFlows: Record<string, Array<{ action: ApprovalLog['action']; from: IEPStatus; to: IEPStatus; comment: string }>> = {
  iep1: [
    { action: '提交草稿', from: '草稿', to: '草稿', comment: '创建IEP计划' },
    { action: '提交审核', from: '草稿', to: '审核中', comment: '提交审核，请审批' },
    { action: '审批通过', from: '审核中', to: '已通过', comment: '计划制定完整，审批通过' },
    { action: '家长签名', from: '已通过', to: '已签名', comment: '家长已确认并签名' },
    { action: '开始执行', from: '已签名', to: '执行中', comment: '开始执行IEP计划' },
  ],
  iep2: [
    { action: '提交草稿', from: '草稿', to: '草稿', comment: '创建IEP计划' },
    { action: '提交审核', from: '草稿', to: '审核中', comment: '请审批该IEP计划' },
  ],
  iep3: [
    { action: '提交草稿', from: '草稿', to: '草稿', comment: '创建IEP计划' },
    { action: '提交审核', from: '草稿', to: '审核中', comment: '提交审核' },
    { action: '审批通过', from: '审核中', to: '已通过', comment: '目标设定合理，审批通过' },
  ],
  iep5: [
    { action: '提交草稿', from: '草稿', to: '草稿', comment: '创建IEP计划' },
    { action: '提交审核', from: '草稿', to: '审核中', comment: '提交审核' },
    { action: '审批通过', from: '审核中', to: '已通过', comment: '审批通过' },
    { action: '家长签名', from: '已通过', to: '已签名', comment: '家长已签名确认' },
    { action: '开始执行', from: '已签名', to: '执行中', comment: '开始执行' },
    { action: '执行完成', from: '执行中', to: '已完成', comment: '所有目标已完成，IEP计划执行完毕' },
  ],
  iep7: [
    { action: '提交草稿', from: '草稿', to: '草稿', comment: '创建IEP计划' },
    { action: '提交审核', from: '草稿', to: '审核中', comment: '提交审核' },
    { action: '审批通过', from: '审核中', to: '已通过', comment: '审批通过' },
    { action: '家长签名', from: '已通过', to: '已签名', comment: '家长已签名' },
    { action: '开始执行', from: '已签名', to: '执行中', comment: '开始执行IEP计划' },
  ],
  iep8: [
    { action: '提交草稿', from: '草稿', to: '草稿', comment: '创建IEP计划' },
    { action: '提交审核', from: '草稿', to: '审核中', comment: '提交审核' },
    { action: '审批驳回', from: '审核中', to: '已驳回', comment: '目标设定不够具体，需要补充成功标准和教学策略' },
  ],
  iep11: [
    { action: '提交草稿', from: '草稿', to: '草稿', comment: '创建IEP计划' },
    { action: '提交审核', from: '草稿', to: '审核中', comment: '提交审核' },
    { action: '审批通过', from: '审核中', to: '已通过', comment: '审批通过' },
    { action: '家长签名', from: '已通过', to: '已签名', comment: '家长已签名确认' },
    { action: '开始执行', from: '已签名', to: '执行中', comment: '开始执行' },
  ],
};

Object.entries(approvalFlows).forEach(([iepId, flows]) => {
  flows.forEach((flow, index) => {
    mockApprovalLogs.push({
      id: `log${logId}`,
      iep_plan_id: iepId,
      action: flow.action,
      from_status: flow.from,
      to_status: flow.to,
      operator: index === 0 ? allTeachers[Math.floor(Math.random() * allTeachers.length)] : '教学主任',
      operator_role: index === 0 ? '班主任' : '教学主任',
      comment: flow.comment,
      created_at: d(index * 5),
    });
    logId++;
  });
});

// Generate parent signatures
export const mockSignatures: ParentSignature[] = mockIEPPlans.map((plan) => ({
  id: `sig${plan.id}`,
  iep_plan_id: plan.id,
  parent_name: plan.student_name.substring(0, 1) + '家长',
  signature_data: plan.signed ? 'data:image/png;base64,mockSignatureData' : null,
  signed_at: plan.signed ? d(20) : null,
  status: plan.signed ? '已签名' as const : '待签名' as const,
}));

// Generate services
export const mockServices: IEPService[] = [];
let svcId = 1;

mockIEPPlans.forEach((plan) => {
  const services: IEPService[] = [
    {
      id: `svc${svcId++}`,
      iep_plan_id: plan.id,
      service_type: '认知训练',
      frequency: '每周3次',
      duration: '30分钟',
      teacher: plan.primary_teacher,
      location: '个训室',
    },
    {
      id: `svc${svcId++}`,
      iep_plan_id: plan.id,
      service_type: '语言治疗',
      frequency: '每周2次',
      duration: '45分钟',
      teacher: plan.team_members[0] || '李老师',
      location: '语言室',
    },
    {
      id: `svc${svcId++}`,
      iep_plan_id: plan.id,
      service_type: '感觉统合',
      frequency: '每周2次',
      duration: '40分钟',
      teacher: plan.team_members[1] || '王老师',
      location: '感统室',
    },
  ];
  mockServices.push(...services);
});
